### ISSUE TITLE
Features | Checklist

### ISSUE THREAD

**Issue by Ssionn** [nonbots/nhanify#1]
# Public Playlists Page
- [x] Make the table width a little bigger so you can read the playlist title if it's longer than intended (For desktop only, Mobile is  fine)

# General
- [ ] People have to have at least 1 song in the playlist to be able to make a playlist
- [ ] Add id hashing for the URL, since the id is publicly available
- [ ] Make playlists not refresh when you scroll through pagination
- [x] Make the songs in the playlist look clickable (They aren't right now)
- [x] Add some spacing to the form where you add a song
- [ ] Make the buttons where you can add a contributor more obvious for the user
- [ ] Make the amount of songs more obvious for the user.

# New Features
- [ ] People are able to like each others playlist
- [ ] See the amount of the hours on a playlist
- [ ] Able to add images for the playlists
- [ ] Show profile picture next to the user of their public playlist
- [ ] Be able to edit the youtube links when editing a song

### Settings features
- [ ] People can add their own profile pictures
